# Generated by Django 6.0.5 on 2026-05-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('restaurant_admin', 'Restaurant Admin'), ('cashier', 'Cashier'), ('waiter', 'Waiter'), ('kitchen', 'Kitchen'), ('manager', 'Manager'), ('delivery', 'Delivery')], default='cashier', max_length=30),
        ),
    ]
