# Generated by Django 6.0.5 on 2026-05-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_role_customeraddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraddress',
            name='full_address',
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='address_line_1',
            field=models.CharField(default=14, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, blank=True, null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, blank=True, null=True),
            preserve_default=False,
        ),
    ]
