# Generated by Django 6.0.5 on 2026-05-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
