# Generated by Django 6.0.5 on 2026-06-01 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_customeraddress_customer_and_more'),
        ('orders', '0009_alter_order_delivery_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerAddress',
        ),
    ]
