# Generated by Django 6.0.5 on 2026-05-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurant_address_alter_restaurant_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
