# Generated by Django 6.0.5 on 2026-05-14 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_floor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area_type', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('vip', 'VIP'), ('smoking', 'Smoking')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='restaurants.floor')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('floor', 'name')},
            },
        ),
    ]
