# Generated by Django 6.0.5 on 2026-05-14 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_area'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='area',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='area',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='restaurants.restaurant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='area',
            name='area_type',
            field=models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('vip', 'VIP'), ('smoking', 'Smoking')], default='indoor', max_length=20),
        ),
    ]
