# Generated by Django 6.0.5 on 2026-05-15 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_restauranttable'),
    ]

    operations = [
        migrations.AddField(
            model_name='restauranttable',
            name='is_merged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restauranttable',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_tables', to='restaurants.restauranttable'),
        ),
    ]
