# Generated by Django 6.0.5 on 2026-06-01 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_restaurant_latitude_restaurant_longitude'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='area',
            unique_together={('restaurant', 'floor', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='restauranttable',
            unique_together={('restaurant', 'floor', 'table_number')},
        ),
    ]
