# Generated by Django 6.0.5 on 2026-05-22 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_delivery_charge_order_service_charge_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='waiter',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'waiter'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiter_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
