# Generated by Django 6.0.5 on 2026-05-28 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='orders.orderitem')),
            ],
        ),
    ]
