# Generated by Django 6.0.5 on 2026-05-28 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitemtax'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAddonTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='orders.orderitemaddon')),
            ],
        ),
        migrations.CreateModel(
            name='OrderComboItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('variant_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('allocated_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_items', to='orders.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='OrderComboItemTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('combo_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='orders.ordercomboitem')),
            ],
        ),
    ]
