# Generated by Django 6.0.5 on 2026-05-30 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customeraddress_location_updated_at'),
        ('orders', '0007_order_delivery_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.customeraddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('unassigned', 'Unassigned'), ('assigned', 'Assigned'), ('picked_up', 'Picked Up'), ('on_the_way', 'On The Way'), ('delivered', 'Delivered')], default='unassigned', max_length=20),
        ),
    ]
