# Generated by Django 6.0.5 on 2026-06-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_inventory_deducted'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
