# Generated by Django 6.0.5 on 2026-06-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_orderitem_ready_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='ready_at',
        ),
        migrations.AddField(
            model_name='order',
            name='ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
