# Generated by Django 6.0.5 on 2026-06-03 16:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
        ('orders', '0012_remove_orderitem_ready_at_order_ready_at'),
        ('restaurants', '0011_alter_area_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='activitylog',
            name='audits_acti_restaur_644196_idx',
        ),
        migrations.RemoveIndex(
            model_name='activitylog',
            name='audits_acti_order_i_e47e57_idx',
        ),
        migrations.RemoveIndex(
            model_name='activitylog',
            name='audits_acti_user_id_3cf657_idx',
        ),
        migrations.RemoveIndex(
            model_name='activitylog',
            name='audits_acti_action_364316_idx',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('order_created', 'Order Created'), ('order_updated', 'Order Updated'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('served', 'Served'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('waiter_changed', 'Waiter Changed'), ('delivery_accepted', 'Delivery Accepted'), ('picked_up', 'Picked Up'), ('on_the_way', 'On The Way'), ('delivered', 'Delivered')], db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['restaurant'], name='audits_acti_restaur_a62c01_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user'], name='audits_acti_user_id_ed8178_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['order'], name='audits_acti_order_i_0fd62a_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action'], name='audits_acti_action_2309cd_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['created_at'], name='audits_acti_created_61d37a_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['restaurant', 'created_at'], name='audits_acti_restaur_403caf_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['restaurant', 'action'], name='audits_acti_restaur_e88621_idx'),
        ),
    ]
