# Generated by Django 6.0.5 on 2026-06-04 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0003_alter_activitylog_action'),
        ('orders', '0012_remove_orderitem_ready_at_order_ready_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
    ]
