# Generated by Django 6.0.5 on 2026-06-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0004_alter_activitylog_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('order_created', 'Order Created'), ('order_updated', 'Order Updated'), ('order_deleted', 'Order Deleted'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('served', 'Served'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('waiter_changed', 'Waiter Changed'), ('delivery_accepted', 'Delivery Accepted'), ('picked_up', 'Picked Up'), ('on_the_way', 'On The Way'), ('delivered', 'Delivered'), ('device_logout', 'Device Logout'), ('all_devices_logout', 'All Devices Logout'), ('forced_logout', 'Forced Logout')], db_index=True, max_length=50),
        ),
    ]
