# Generated by Django 6.0.5 on 2026-05-18 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='cost_price',
            new_name='cost_per_unit',
        ),
    ]
