# Generated by Django 6.0.5 on 2026-05-18 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_cost_price_ingredient_cost_per_unit'),
        ('menu', '0006_dynamicpricing_productdynamicpricing'),
        ('restaurants', '0009_restauranttable_is_merged_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='menu.combo')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_recipes', to='menu.productvariant')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_recipes', to='restaurants.restaurant')),
            ],
            options={
                'unique_together': {('combo', 'product_variant')},
            },
        ),
        migrations.CreateModel(
            name='ProductRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_recipes', to='inventory.ingredient')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='menu.productvariant')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_recipes', to='restaurants.restaurant')),
            ],
            options={
                'unique_together': {('product_variant', 'ingredient')},
            },
        ),
    ]
