# Generated by Django 6.0.5 on 2026-06-04 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0011_alter_area_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField()),
                ('device_name', models.CharField(blank=True, max_length=255)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('login_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_activity', models.DateTimeField(auto_now=True, db_index=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to='restaurants.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['restaurant'], name='security_us_restaur_c11fbf_idx'), models.Index(fields=['user'], name='security_us_user_id_ec746f_idx'), models.Index(fields=['is_active'], name='security_us_is_acti_9806e2_idx'), models.Index(fields=['login_at'], name='security_us_login_a_f98add_idx'), models.Index(fields=['last_activity'], name='security_us_last_ac_9080e9_idx'), models.Index(fields=['restaurant', 'is_active'], name='security_us_restaur_5311b2_idx')],
            },
        ),
    ]
