# Generated by Django 6.0.5 on 2026-05-15 11:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('restaurants', '0009_restauranttable_is_merged_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addon',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='combo',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='tax',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='addon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addon',
            name='restaurant',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='restaurants.restaurant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='combo',
            name='restaurant',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='combos', to='restaurants.restaurant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='restaurant',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='restaurants.restaurant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='restaurant',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='restaurants.restaurant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='restaurant',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='restaurants.restaurant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tax',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tax',
            name='restaurant',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='restaurants.restaurant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='restaurants.restaurant'),
        ),
        migrations.AlterField(
            model_name='comboitem',
            name='combo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_items', to='menu.combo'),
        ),
        migrations.AlterField(
            model_name='comboitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_combos', to='menu.product'),
        ),
        migrations.AlterField(
            model_name='offerproduct',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_products', to='menu.offer'),
        ),
        migrations.AlterField(
            model_name='offerproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_offers', to='menu.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='menu.category'),
        ),
        migrations.AlterField(
            model_name='productaddon',
            name='addon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_products', to='menu.addon'),
        ),
        migrations.AlterField(
            model_name='productaddon',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_addons', to='menu.product'),
        ),
        migrations.AlterField(
            model_name='producttax',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_taxes', to='menu.product'),
        ),
        migrations.AlterField(
            model_name='producttax',
            name='tax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_products', to='menu.tax'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='menu.product'),
        ),
        migrations.AlterUniqueTogether(
            name='addon',
            unique_together={('restaurant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('restaurant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='combo',
            unique_together={('restaurant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='comboitem',
            unique_together={('combo', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='offerproduct',
            unique_together={('offer', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('restaurant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='productaddon',
            unique_together={('product', 'addon')},
        ),
        migrations.AlterUniqueTogether(
            name='producttax',
            unique_together={('product', 'tax')},
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='tax',
            unique_together={('restaurant', 'name')},
        ),
    ]
