# Generated by Django 6.0.5 on 2026-05-17 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_addon_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['product', 'id']},
        ),
        migrations.RenameField(
            model_name='combo',
            old_name='price',
            new_name='combo_price',
        ),
        migrations.AddField(
            model_name='combo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='combo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='combo_images/'),
        ),
        migrations.AlterField(
            model_name='combo',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='ComboProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_products', to='menu.combo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_combos', to='menu.product')),
            ],
            options={
                'unique_together': {('combo', 'product')},
            },
        ),
        migrations.DeleteModel(
            name='ComboItem',
        ),
    ]
