# Generated by Django 6.0.5 on 2026-05-17 12:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_productvariant_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producttax',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='producttax',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producttax',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_tax', to='menu.product'),
        ),
    ]
