# Generated by Django 6.0.5 on 2026-05-17 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_producttax_unique_together_servicecharge'),
        ('restaurants', '0009_restauranttable_is_merged_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('pricing_type', models.CharField(choices=[('percentage_increase', 'Percentage Increase'), ('flat_increase', 'Flat Increase'), ('percentage_discount', 'Percentage Discount'), ('flat_discount', 'Flat Discount')], max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('days', models.CharField(blank=True, help_text='mon,tue,wed', max_length=100, null=True)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_pricings', to='restaurants.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDynamicPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dynamic_pricing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='menu.dynamicpricing')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_pricings', to='menu.product')),
            ],
            options={
                'unique_together': {('product', 'dynamic_pricing')},
            },
        ),
    ]
