# Generated by Django 6.0.5 on 2026-05-21 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_dynamicpricing_productdynamicpricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboDynamicPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_pricings', to='menu.combo')),
                ('dynamic_pricing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combos', to='menu.dynamicpricing')),
            ],
            options={
                'unique_together': {('combo', 'dynamic_pricing')},
            },
        ),
    ]
