# Generated by Django 6.0.5 on 2026-05-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_combodynamicpricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecharge',
            name='apply_on',
            field=models.CharField(choices=[('all', 'All Orders'), ('dine_in', 'Dine In'), ('takeaway', 'Takeaway'), ('delivery', 'Delivery')], default='all', max_length=20),
        ),
    ]
