# Generated by Django 6.0.5 on 2026-05-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_servicecharge_apply_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecharge',
            name='apply_on',
        ),
        migrations.AddField(
            model_name='servicecharge',
            name='order_type',
            field=models.CharField(choices=[('all', 'All'), ('dine_in', 'Dine In'), ('takeaway', 'Takeaway'), ('delivery', 'Delivery')], default='all', max_length=20),
        ),
    ]
