# Generated by Django 6.0.5 on 2026-05-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_remove_servicecharge_apply_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecharge',
            name='order_type',
        ),
        migrations.AddField(
            model_name='servicecharge',
            name='applicable_order_types',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
