# Generated by Django 6.0.5 on 2026-05-27 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_remove_servicecharge_order_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecharge',
            name='auto_apply',
        ),
    ]
